"""Generátor GDScript instalačních skriptů"""

from typing import Dict, List, Any
from jinja2 import Template
from app.core.exceptions import GenerationException


class GDScriptGenerator:
    """Generátor instalačních GDScript skriptů z blueprintu"""
    
    def __init__(self):
        self.installer_template = self._load_installer_template()
        self.script_template = self._load_script_template()
    
    def _load_installer_template(self) -> Template:
        """Načte template pro Installer.gd"""
        template_str = '''@tool
extends EditorScript
# This file is auto-generated by GDForge AI
# Do not edit manually

func _run():
    var root_path = "res://{{ project_root }}"
    _ensure_directory(root_path)
    
    # Generate scenes
    _create_scenes(root_path)
    
    # Generate scripts
    _create_scripts(root_path)
    
    # Generate resources
    _create_resources(root_path)
    
    # Connect signals
    _connect_signals(root_path)
    
    print("✓ GDForge project initialized successfully!")
    print("Created: {{ summary }}")


func _ensure_directory(path: String) -> void:
    var dir = DirAccess.open(path)
    if dir == null:
        DirAccess.make_dir_recursive_absolute(path)


func _create_scenes(root_path: String) -> void:
    """Creates all scene files"""
{%- for scene in scenes %}
    _create_scene_{{ loop.index0 }}(root_path)
{%- endfor %}


func _create_scripts(root_path: String) -> void:
    """Creates all script files"""
{%- for script in scripts %}
    _create_script_{{ loop.index0 }}(root_path)
{%- endfor %}


func _create_resources(root_path: String) -> void:
    """Creates all resource files"""
{%- for resource in resources %}
    _create_resource_{{ loop.index0 }}(root_path)
{%- endfor %}


func _connect_signals(root_path: String) -> void:
    """Connects signals between nodes"""
{%- for signal in signals %}
    _connect_signal_{{ loop.index0 }}(root_path)
{%- endfor %}


{%- for scene in scenes %}

func _create_scene_{{ loop.index0 }}(root_path: String) -> void:
    var scene_path = root_path + "/{{ scene.path }}"
    _ensure_directory(scene_path.get_basename())
    
    if ResourceLoader.exists(scene_path):
        print("⚠ Scene already exists: %s" % scene_path)
        return
    
    var root = {{ scene.root_node.type }}.new()
    root.name = "{{ scene.root_node.name }}"
    
{%- for node in scene.nodes %}
    var node_{{ loop.index0 }} = {{ node.type }}.new()
    node_{{ loop.index0 }}.name = "{{ node.name }}"
{%- for prop_name, prop_value in node.properties.items() %}
    node_{{ loop.index0 }}.{{ prop_name }} = {{ prop_value }}
{%- endfor %}
    root.add_child(node_{{ loop.index0 }})
    node_{{ loop.index0 }}.owner = root
{%- endfor %}

{%- if scene.script %}
    if ResourceLoader.exists("{{ scene.script }}"):
        root.set_script(load("{{ scene.script }}"))
{%- endif %}
    
    var packed_scene = PackedScene.new()
    packed_scene.pack(root)
    ResourceSaver.save(packed_scene, scene_path)
    print("✓ Scene created: %s" % scene_path)

{%- endfor %}


{%- for script in scripts %}

func _create_script_{{ loop.index0 }}(root_path: String) -> void:
    var script_path = root_path + "/{{ script.path }}"
    _ensure_directory(script_path.get_basename())
    
    if ResourceLoader.exists(script_path):
        print("⚠ Script already exists: %s" % script_path)
        return
    
    var script_content = """{{ script.content | replace('"""', '\\"\\"\\"') }}"""
    
    var file = FileAccess.open(script_path, FileAccess.WRITE)
    if file == null:
        print("✗ Failed to create script: %s" % script_path)
        return
    
    file.store_string(script_content)
    print("✓ Script created: %s" % script_path)

{%- endfor %}


{%- for resource in resources %}

func _create_resource_{{ loop.index0 }}(root_path: String) -> void:
    var resource_path = root_path + "/{{ resource.path }}"
    _ensure_directory(resource_path.get_basename())
    
    if ResourceLoader.exists(resource_path):
        print("⚠ Resource already exists: %s" % resource_path)
        return
    
    var resource = {{ resource.type }}.new()
{%- for prop_name, prop_value in resource.properties.items() %}
    resource.{{ prop_name }} = {{ prop_value }}
{%- endfor %}
    
    ResourceSaver.save(resource, resource_path)
    print("✓ Resource created: %s" % resource_path)

{%- endfor %}


{%- for signal in signals %}

func _connect_signal_{{ loop.index0 }}(root_path: String) -> void:
    var scene_path = root_path + "/{{ signal.scene }}"
    if not ResourceLoader.exists(scene_path):
        return
    
    var scene = load(scene_path).instantiate()
    var emitter = scene.get_node("{{ signal.emitter }}")
    var receiver = scene.get_node("{{ signal.receiver }}")
    
    if emitter and receiver:
        emitter.connect("{{ signal.signal_name }}", Callable(receiver, "{{ signal.handler }}"))
        print("✓ Signal connected: {{ signal.emitter }}.{{ signal.signal_name }} -> {{ signal.handler }}")
    
    scene.queue_free()

{%- endfor %}
'''
        return Template(template_str)
    
    def _load_script_template(self) -> Template:
        """Načte template pro GDScript soubory"""
        template_str = '''# Auto-generated by GDForge AI
# File: {{ path }}

{%- if class_name %}
class_name {{ class_name }}
{%- endif %}

extends {{ extends }}


{%- for prop in properties %}

## Property: {{ prop.name }}
var {{ prop.name }}: {{ prop.type }}
{%- if prop.default %} = {{ prop.default }}
{%- endif %}
{%- endfor %}


{%- for method in methods %}

## {{ method.docstring }}
{{ method.signature }}
    pass

{%- endfor %}
'''
        return Template(template_str)
    
    def generate(self, blueprint: Dict[str, Any], project_root: str = "scenes") -> str:
        """
        Generuje kompletní Installer.gd ze blueprintu
        
        Args:
            blueprint: Strukturovaný plán ze LLM
            project_root: Kořenový adresář pro vytváření souborů
            
        Returns:
            str: Kompletní GDScript kód Installer.gd
        """
        try:
            # Validuj blueprint
            self._validate_blueprint(blueprint)
            
            # Generuj obsahy skriptů
            scripts = blueprint.get("scripts", [])
            for script in scripts:
                if "content" not in script:
                    script["content"] = self._generate_script_content(script)
            
            # Normalizuj cesty
            for scene in blueprint.get("scenes", []):
                if not scene["path"].startswith("res://"):
                    scene["path"] = f"res://{project_root}/{scene['path']}"
            
            # Generuj Installer.gd
            installer_code = self.installer_template.render(
                scenes=blueprint.get("scenes", []),
                scripts=blueprint.get("scripts", []),
                resources=blueprint.get("resources", []),
                signals=blueprint.get("signals", []),
                project_root=project_root,
                summary=blueprint.get("summary", "GDForge project")
            )
            
            return installer_code
            
        except Exception as e:
            raise GenerationException(f"Failed to generate installer: {str(e)}")
    
    def _validate_blueprint(self, blueprint: Dict[str, Any]) -> None:
        """Validuje strukturu blueprintu"""
        if not isinstance(blueprint, dict):
            raise GenerationException("Blueprint must be a dictionary")
        
        required_keys = ["scenes", "scripts", "resources"]
        for key in required_keys:
            if key not in blueprint:
                raise GenerationException(f"Missing required key: {key}")
    
    def _generate_script_content(self, script: Dict[str, Any]) -> str:
        """Generuje obsah GDScript souboru"""
        return self.script_template.render(
            path=script.get("path", ""),
            class_name=script.get("class_name", ""),
            extends=script.get("extends", "Node"),
            properties=script.get("properties", []),
            methods=script.get("methods", [])
        )
